# Generated by Django 4.2.20 on 2025-08-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app7_account', '0002_alter_userprofile_academicyear_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='lab',
            field=models.CharField(default='General', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(default='Staff', max_length=50),
            preserve_default=False,
        ),
    ]
